[package]
name = "evm_rpc_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-timers = "0.10" # Feel free to remove this dependency if you don't need timers
num-traits = "0.2.19"
hex = "0.4.3"
sha2 = "0.10.6"
getrandom = { version = "0.2", features = ["custom"] }
k256 = { version = "0.12.0", features = ["ecdsa"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"  # Direct version
serde_json = "1.0"    # Direct version
ethers-core = "2.0"   # Direct version
evm-rpc-canister-types = "4.0.1"  # Direct version
futures = "0.3"
